### ISSUE TITLE
ModuleNotFoundError: No module named 'rts'

### ISSUE THREAD

**Issue by carlosgmartin** [vwxyzjn/gym-microrts#9]
After following the instructions in the README and trying to run `python3 hello_world.py`, I'm getting the following error:

```
ModuleNotFoundError: No module named 'rts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hello_world.py", line 21, in <module>
    print(e.stacktrace())
AttributeError: 'ModuleNotFoundError' object has no attribute 'stacktrace'
```

**Comment by vwxyzjn** [comment]
Hello, is this the latest version?

**Comment by carlosgmartin** [comment]
Thanks, I followed the new README and it seems to work now.

What's the right way to end execution of `hello_world.py`? `SIGINT` and `SIGQUIT` don't work. I also notice `env.close()` is commented out in `hello_world.py`.

**Comment by vwxyzjn** [comment]
Great to hear that. Try `env.close()`

**Comment by carlosgmartin** [comment]
I uncommented `env.close()` but the problem persists. Trying to send `SIGINT` (`Ctrl`+`C`) yields

```
Disposal was interrupted:
java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Object.java:321)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1361)
	at java.desktop/java.awt.Window.doDispose(Window.java:1224)
	at java.desktop/java.awt.Window.dispose(Window.java:1161)
	at tests.JNIClient.close(JNIClient.java:325)
```

After that, trying to send `SIGQUIT` (`Ctrl`+`\`) yields

```
Full thread dump Java HotSpot(TM) 64-Bit Server VM (15+36-1562 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x00007fc4e25d14b0, length=15, elements={
0x00007fc4dc008200, 0x00007fc4dd273000, 0x00007fc4dd280400, 0x00007fc4dc868a00,
0x00007fc4dc86aa00, 0x00007fc4dc86b000, 0x00007fc4dc0a2400, 0x00007fc4dd288400,
0x00007fc4dc0c4c00, 0x00007fc4dc091000, 0x00007fc4de0daa00, 0x00007fc4dc211e00,
0x00007fc4dcd7e400, 0x00007fc4dcd7ea00, 0x00007fc4dd67f600
}

"main" #1 prio=5 os_prio=31 cpu=2503.43ms elapsed=125.03s tid=0x00007fc4dc008200 nid=0x307 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Reference Handler" #2 daemon prio=10 os_prio=31 cpu=2.49ms elapsed=125.02s tid=0x00007fc4dd273000 nid=0x4103 waiting on condition  [0x0000700008d10000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@15/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@15/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@15/Reference.java:213)
```

and many more lines.

**Comment by vwxyzjn** [comment]
Hi this problem is likely an upstream bug from jpype, which we use to interface microrts with the python code. See https://github.com/jpype-project/jpype/issues/556 for more info.

**Comment by vwxyzjn** [comment]
Some workaround i have often used is to use `raise` at certain position to stop the code execution.

**Comment by carlosgmartin** [comment]
It looks like the jpype issue was closed again. I'm still experiencing the same problem after reinstalling gym-microrts. Are there any other changes I need to apply?

**Comment by vwxyzjn** [comment]
@carlosgmartin feel free to update your Jpype and see if the issue persists. Per the conversation in the issue, I am not sure if they have pushed the fix for Ctrl C to the latest version yet.

**Comment by carlosgmartin** [comment]
Thanks. I updated jpype with `pip3 install git+https://github.com/jpype-project/jpype.git` and it seems to work now. Is there an option to disable printing the following lines?

```
[parent directory]/gym-microrts/microrts/maps/10x10/basesWorkers10x10.xml
[Lai.rewardfunction.RewardFunctionInterface;@15975490
done
```

**Comment by vwxyzjn** [comment]
@carlosgmartin Great to hear. The printing comes from https://github.com/vwxyzjn/microrts/blob/a27507fed37aee0f3526c022ef5b315e4e880fd0/src/tests/JNIClient.java#L140. Right now you have compile to disable the printings.

So when you run the `hello_world.py` with the Monitor wrapper, does it save the video at least? Also what operating system are you running on?

**Comment by carlosgmartin** [comment]
> Right now you have compile to disable the printings.

Sorry, can you clarify what you mean?

> So when you run the hello_world.py with the Monitor wrapper, does it save the video at least? 

Yes.

> Also what operating system are you running on?

macOS Catalina 10.15.7.
